version: '3.8'

services:
  shiftscheduler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    restart: unless-stopped
    container_name: shiftscheduler-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s